#spring
spring:
  devtools:
    restart:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.106.131.156:3306/blog?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: pool-vscloud
      connectionTestQuery: SELECT 1
      maximum-pool-size: 50
      minimum-idle: 10
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    cache: false
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.acfun.core.entity
  typeEnumsPackage: com.acfun.core.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.servingcloud.vscloud.core.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    meta-object-handler: com.acfun.core.handler.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.servingcloud.vscloud.core
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  config: classpath:logback-spring.xml
  level: debugswagger

swagger.show: true
path: D:\work\photo

